mod color_palette;
mod county;
mod data;
mod data_category;
mod data_source;
mod dataset;
mod map_visualization;
mod map_visualization_collection;
mod scale_type;
mod state;
mod subcategory;
mod upload_metadata;

pub type DataSource = data_source::DataSource;
pub type DataSourceDiff = data_source::DataSourceDiff;
pub type State = state::State;
pub type County = county::County;
pub type Data = data::Data;
pub type NewData = data::NewData;
pub type SimpleData = data::SimpleData;
pub type PercentileData = data::PercentileData;
pub type SourceAndDate = data::SourceAndDate;
pub type Dataset = dataset::Dataset;
pub type DatasetDiff = dataset::DatasetDiff;
pub type MapVisualization = map_visualization::MapVisualization;
pub type MapVisualizationDaoPatch = map_visualization::MapVisualizationDaoPatch;
pub type MapVisualizationPatch = map_visualization::MapVisualizationPatch;
pub type MapVisualizationModel = map_visualization::MapVisualizationModel;
pub type DataCategory = data_category::DataCategory;
pub type DataCategoryCreation = data_category::DataCategoryCreation;
pub type ColorPalette = color_palette::ColorPalette;
pub type ScaleType = scale_type::ScaleType;
pub type MapVisualizationError = map_visualization::MapVisualizationError;
pub type Subcategory = subcategory::Subcategory;
pub type MapVisualizationCollection = map_visualization_collection::MapVisualizationCollection;
pub type MapVisualizationCollectionId = map_visualization_collection::MapVisualizationCollectionId;
pub type UploadMetadata = upload_metadata::UploadMetadata;
pub type NewDataSource = data_source::NewDataSource;
pub type Source = upload_metadata::Source;
pub type NewDataset = upload_metadata::NewDataset;
