mod color_palette;
mod county;
mod data;
mod data_category;
mod data_source;
mod dataset;
mod map_visualization;
mod scale_type;
mod state;

pub type DataSource = data_source::DataSource;
pub type State = state::State;
pub type County = county::County;
pub type USACountyData = data::USACountyData;
pub type USACountySimpleData = data::USACountySimpleData;
pub type CountryData = data::CountryData;
pub type CountrySimpleData = data::CountrySimpleData;
pub type USACountyPercentileData = data::USACountyPercentileData;
pub type SourceAndDate = data::SourceAndDate;
pub type Dataset = dataset::Dataset;
pub type MapVisualization = map_visualization::MapVisualization;
pub type MapVisualizationDaoPatch = map_visualization::MapVisualizationDaoPatch;
pub type MapVisualizationPatch = map_visualization::MapVisualizationPatch;
pub type MapVisualizationModel = map_visualization::MapVisualizationModel;
pub type DataCategory = data_category::DataCategory;
pub type ColorPalette = color_palette::ColorPalette;
pub type ScaleType = scale_type::ScaleType;
