import { Map } from 'immutable'

export enum State {
    Alabama = 1,
    Alaska = 2,
    Arizona = 4,
    Arkansas = 5,
    California = 6,
    Colorado = 8,
    Connecticut = 9,
    Delaware = 10,
    DC = 11,
    Florida = 12,
    Georgia = 13,
    Hawaii = 15,
    Idaho = 16,
    Illinois = 17,
    Indiana = 18,
    Iowa = 19,
    Kansas = 20,
    Kentucky = 21,
    Louisiana = 22,
    Maine = 23,
    Maryland = 24,
    Massachusetts = 25,
    Michigan = 26,
    Minnesota = 27,
    Mississippi = 28,
    Missouri = 29,
    Montana = 30,
    Nebraska = 31,
    Nevada = 32,
    New_Hampshire = 33,
    New_Jersey = 34,
    New_Mexico = 35,
    New_York = 36,
    North_Carolina = 37,
    North_Dakota = 38,
    Ohio = 39,
    Oklahoma = 40,
    Oregon = 41,
    Pennsylvania = 42,
    Rhode_Island = 44,
    South_Carolina = 45,
    South_Dakota = 46,
    Tennessee = 47,
    Texas = 48,
    Utah = 49,
    Vermont = 50,
    Virginia = 51,
    Washington = 53,
    West_Virginia = 54,
    Wisconsin = 55,
    Wyoming = 56,
    American_Samoa = 60,
    Guam = 66,
    Northern_Mariana_Islands = 69,
    Puerto_Rico = 72,
    US_Minor_Outlying_Islands = 74,
    US_Virgin_Islands = 78,
}

export default Map([
    [State.Alabama, 'Alabama'],
    [State.Alaska, 'Alaska'],
    [State.Arizona, 'Arizona'],
    [State.Arkansas, 'Arkansas'],
    [State.California, 'California'],
    [State.Colorado, 'Colorado'],
    [State.Connecticut, 'Connecticut'],
    [State.Delaware, 'Delaware'],
    [State.DC, 'D.C.'],
    [State.Florida, 'Florida'],
    [State.Georgia, 'Georgia'],
    [State.Hawaii, 'Hawaii'],
    [State.Idaho, 'Idaho'],
    [State.Illinois, 'Illinois'],
    [State.Indiana, 'Indiana'],
    [State.Iowa, 'Iowa'],
    [State.Kansas, 'Kansas'],
    [State.Kentucky, 'Kentucky'],
    [State.Louisiana, 'Louisiana'],
    [State.Maine, 'Maine'],
    [State.Maryland, 'Maryland'],
    [State.Massachusetts, 'Massachusetts'],
    [State.Michigan, 'Michigan'],
    [State.Minnesota, 'Minnesota'],
    [State.Mississippi, 'Mississippi'],
    [State.Missouri, 'Missouri'],
    [State.Montana, 'Montana'],
    [State.Nebraska, 'Nebraska'],
    [State.Nevada, 'Nevada'],
    [State.New_Hampshire, 'New Hampshire'],
    [State.New_Jersey, 'New Jersey'],
    [State.New_Mexico, 'New Mexico'],
    [State.New_York, 'New York'],
    [State.North_Carolina, 'North Carolina'],
    [State.North_Dakota, 'North Dakota'],
    [State.Ohio, 'Ohio'],
    [State.Oklahoma, 'Oklahoma'],
    [State.Oregon, 'Oregon'],
    [State.Pennsylvania, 'Pennsylvania'],
    [State.Rhode_Island, 'Rhode Island'],
    [State.South_Carolina, 'South Carolina'],
    [State.South_Dakota, 'South Dakota'],
    [State.Tennessee, 'Tennessee'],
    [State.Texas, 'Texas'],
    [State.Utah, 'Utah'],
    [State.Vermont, 'Vermont'],
    [State.Virginia, 'Virginia'],
    [State.Washington, 'Washington'],
    [State.West_Virginia, 'West Virginia'],
    [State.Wisconsin, 'Wisconsin'],
    [State.Wyoming, 'Wyoming'],
    [State.American_Samoa, 'American Samoa'],
    [State.Guam, 'Guam'],
    [State.Northern_Mariana_Islands, 'Northern Mariana Islands'],
    [State.Puerto_Rico, 'Puerto Rico'],
    [State.US_Minor_Outlying_Islands, 'U.S. Minor Outlying Islands'],
    [State.US_Virgin_Islands, 'U.S. Virgin Islands'],
])
