name: Build And Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ⚡ Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: 🔨 Build
        run: cargo build --release --verbose
        working-directory: backend
      - name: 🧪 Test
        run: cargo test
        working-directory: backend

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"
      - name: 🔨 Build
        run: |
          yarn install --frozen-lockfile
          yarn tsc
          yarn lint
          yarn build
        working-directory: frontend
      - name: 🧪 Test
        run: yarn test
        working-directory: frontend
